plugins:
  - name: proxy-rewrite

routes:
  - uri: /issuer/prism-agent/*
    upstream_id: 1
    plugins:
      proxy-rewrite:
        regex_uri: ["^/issuer/prism-agent/(.*)", "/$1"]
  - uri: /issuer/cloud-agent/*
    upstream_id: 1
    plugins:
      proxy-rewrite:
        regex_uri: ["^/issuer/cloud-agent/(.*)", "/$1"]
  - uri: /issuer/didcomm*
    upstream_id: 2
    plugins:
      proxy-rewrite:
        regex_uri: ["^/issuer/didcomm(.*)", "/$1"]

  - uri: /verifier/prism-agent/*
    upstream_id: 3
    plugins:
      proxy-rewrite:
        regex_uri: ["^/verifier/prism-agent/(.*)", "/$1"]
  - uri: /verifier/cloud-agent/*
    upstream_id: 3
    plugins:
      proxy-rewrite:
        regex_uri: ["^/verifier/cloud-agent/(.*)", "/$1"]
  - uri: /verifier/didcomm*
    upstream_id: 4
    plugins:
      proxy-rewrite:
        regex_uri: ["^/verifier/didcomm(.*)", "/$1"]

  - uri: /holder/prism-agent/*
    upstream_id: 5
    plugins:
      proxy-rewrite:
        regex_uri: ["^/holder/prism-agent/(.*)", "/$1"]
  - uri: /holder/cloud-agent/*
    upstream_id: 5
    plugins:
      proxy-rewrite:
        regex_uri: ["^/holder/cloud-agent/(.*)", "/$1"]
  - uri: /holder/didcomm*
    upstream_id: 6
    plugins:
      proxy-rewrite:
        regex_uri: ["^/holder/didcomm(.*)", "/$1"]

upstreams:
  - id: 1
    nodes:
      "issuer-agent:8085": 1 # tapir
    type: roundrobin
    timeout:
      connect: 900
      send: 900
      read: 900
  - id: 2
    nodes:
      "issuer-agent:8090": 1 # didcom
    type: roundrobin
    timeout:
      connect: 900
      send: 900
      read: 900
  - id: 3
    nodes:
      "verifier-agent:8085": 1 # tapir
    type: roundrobin
    timeout:
      connect: 900
      send: 900
      read: 900
  - id: 4
    nodes:
      "verifier-agent:8090": 1 # didcom
    type: roundrobin
    timeout:
      connect: 900
      send: 900
      read: 900
  - id: 5
    nodes:
      "holder-agent:8085": 1 # tapir
    type: roundrobin
    timeout:
      connect: 900
      send: 900
      read: 900
  - id: 6
    nodes:
      "holder-agent:8090": 1 # didcom
    type: roundrobin
    timeout:
      connect: 900
      send: 900
      read: 900
#END
